import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { APP_LOCALES, type AppLocale } from '@/lib/i18n';
import { validateSeoMetadata } from '@/lib/seo-validation';
import type { ItemFormValue, SeoFormValue } from './types';

export function SeoSection({
  item,
  seo,
  seoRecords,
}: {
  item?: Pick<ItemFormValue, 'title' | 'slug' | 'description' | 'thumbnail_path'>;
  seo?: SeoFormValue | null;
  seoRecords?: SeoFormValue[];
}) {
  const seoByLocale = new Map<AppLocale, SeoFormValue>();
  if (seo) seoByLocale.set('en', seo);
  seoRecords?.forEach((record) => {
    if (record.locale) seoByLocale.set(record.locale, record);
  });

  return (
    <section className="space-y-4 rounded-lg border p-4">
      <div>
        <h2 className="font-semibold">SEO metadata</h2>
        <p className="text-sm text-muted-foreground">
          Manage indexed metadata for English, Russian, and Armenian storefront pages.
        </p>
      </div>
      {APP_LOCALES.map((locale) => {
        const currentSeo = seoByLocale.get(locale);
        const warnings = validateSeoMetadata(
          {
            seo_title: currentSeo?.seo_title ?? null,
            seo_description: currentSeo?.seo_description ?? null,
            seo_slug: currentSeo?.seo_slug ?? item?.slug ?? null,
            keywords: currentSeo?.keywords ?? [],
            og_title: currentSeo?.og_title ?? null,
            og_description: currentSeo?.og_description ?? null,
            social_image_path: currentSeo?.social_image_path ?? item?.thumbnail_path ?? null,
            noindex: currentSeo?.noindex ?? false,
          },
          { requireLocalized: locale !== 'en' },
        );
        const previewTitle = currentSeo?.seo_title || item?.title || 'SEO title preview';
        const previewDescription =
          currentSeo?.seo_description ||
          item?.description ||
          'Meta description preview appears here.';

        return (
          <div key={locale} className="space-y-4 rounded-md border bg-muted/20 p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <h3 className="text-sm font-semibold uppercase tracking-wide">{locale}</h3>
                <p className="text-xs text-muted-foreground">
                  {currentSeo?.generated_by_ai ? 'Generated by AI' : 'Manual metadata'}
                  {currentSeo?.reviewed_by_admin ? ' - reviewed' : ' - needs review'}
                </p>
              </div>
              {warnings.length > 0 && (
                <div className="warning-panel rounded-md border px-3 py-2 text-xs">
                  {warnings.map((warning) => (
                    <div key={warning.code}>{warning.message}</div>
                  ))}
                </div>
              )}
            </div>
            <div className="rounded-md border bg-background p-3">
              <p className="truncate text-sm font-medium text-blue-700">{previewTitle}</p>
              <p className="truncate text-xs text-success">
                /items/{currentSeo?.seo_slug || item?.slug || 'item-slug'}
              </p>
              <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">
                {previewDescription}
              </p>
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor={`seoTitle_${locale}`}>SEO title</Label>
                <Input
                  id={`seoTitle_${locale}`}
                  name={`seoTitle_${locale}`}
                  defaultValue={currentSeo?.seo_title ?? ''}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor={`seoKeywords_${locale}`}>Keywords</Label>
                <Input
                  id={`seoKeywords_${locale}`}
                  name={`seoKeywords_${locale}`}
                  defaultValue={currentSeo?.keywords?.join(', ') ?? ''}
                  placeholder="wooden gift, night light"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor={`seoDescription_${locale}`}>Meta description</Label>
              <Textarea
                id={`seoDescription_${locale}`}
                name={`seoDescription_${locale}`}
                defaultValue={currentSeo?.seo_description ?? ''}
              />
            </div>
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label htmlFor={`ogTitle_${locale}`}>Open Graph title</Label>
                <Input
                  id={`ogTitle_${locale}`}
                  name={`ogTitle_${locale}`}
                  defaultValue={currentSeo?.og_title ?? ''}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor={`socialImagePath_${locale}`}>Social image path</Label>
                <p className="text-xs text-muted-foreground">
                  Recommended 1200x630 px for Open Graph sharing.
                </p>
                <Input
                  id={`socialImagePath_${locale}`}
                  name={`socialImagePath_${locale}`}
                  defaultValue={currentSeo?.social_image_path ?? ''}
                />
                <Input
                  id={`socialImageFile_${locale}`}
                  name={`socialImageFile_${locale}`}
                  type="file"
                  accept="image/png,image/jpeg,image/webp,image/svg+xml"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor={`ogDescription_${locale}`}>Open Graph description</Label>
              <Textarea
                id={`ogDescription_${locale}`}
                name={`ogDescription_${locale}`}
                defaultValue={currentSeo?.og_description ?? ''}
              />
            </div>
          </div>
        );
      })}
    </section>
  );
}
